### PR TITLE
WIP CircleCI Setup

### PR DESCRIPTION
**Pull request by colinrymer**
Need to setup project config to use key `164E1387`

### CODE REVIEW

**Comment by colinrymer** [comment]
@briprowe, @err, @Christopher-Bui, @rickhall2000  you should be able to access the circleci project - https://circleci.com/gh/rentpath/clj-config/ as collaborators of this repo. The `.circle.yml` file included in this PR needs some work to get everything setup to deploy to clojars.

I've created a clojars user with a GPG public key listed and taken the first steps to getting the private key setup on circleci. The key id is listed in the PR description, and it will need to be specified in the project config so it's used and not the other gpg keys available on the machine.

Let me know what I can do to help with this process - I'd like to get it setup so that merges to master automatically push new releases to clojars classic - clojars releases require a manual step still (from what I gathered in the docs).

**Comment by colinrymer** [comment]
s/master/dev (though really, we should switch the default branch back to master unless there are compelling reasons not to - everyone's used to master being the default/main/stable/etc. branch)

**Comment by briprowe** [comment]
@colinrymer @rickhall2000 @err @Christopher-Bui I'm going to see what I can do to get this running this weekend.

**Comment by briprowe** [comment]
@colinrymer How were you planning to manage releases of this code? It doesn't seem like the main `.circle.ym` should automatically deploy, right?

**Comment by briprowe** [comment]
@semperos Just wanted to ping you on this too!

**Comment by colinrymer** [comment]
So a couple things have changed since I last worked on this:

1. It looks like we're going to use Travis-CI for our open source libs - this is actually probably nice since encrypted keys, etc. are much easier to deal with.
2. We'd like to do something like [semantic-release](https://github.com/semantic-release/semantic-release). Ideally we'd also use something like https://github.com/commitizen/cz-cli.

**Comment by Christopher-Bui** [comment]
Colin, I think I'm going to have some free cycles this week so if you need
me to do any of this I can.

**Comment by Christopher-Bui** [comment]
Looks good to me. Colin's out this week so we can change to Travis in another PR. I wouldn't want to get rid of CI builds so I think we should just keep circle for now.

@rickhall2000, @semperos?

**Pull request merged**
